manage_accounts:
  path: "/accounts/.*"
  http_method: 
    - GET
    - put
  permissions:
    - AUTH::VIEW_ACCOUNT
    - AUTH::MANAGE_ACCOUNTS

create_users:
  path: "/users"
  http_method: POST
  permissions:
    - AUTH::CREATE_USERS
  rule: ChronosAuthz::Spec::Helpers::CustomRule

shipment:
  path: "/*"