accounts_page:
  path: "/accounts/*"
  http_method: 
    - GET
    - post
  permissions:
    - AUTH::VIEW_ACCOUNT
    - AUTH::MANAGE_ACCOUNTS

view_users_page:
  path: "/users"
  http_method: GET
  permissions:
    - AUTH::VIEW_USERS
  # rule: AnotherRule

shipment:
  path: "/*"
